


language: node_js
node_js: stable

branches:
  only:
  - dev

before_install:
# 解密SSH
# encrypted_key和encrypted_id可以在travis里setting查看，具体位置参考下图
dd:
- openssl aes-256-cbc -K $encrypted_3b9dd57bb972_key -iv $encrypted_3b9dd57bb972_iv
  -in travis_rsa.enc -out travis_rsa -d
- chmod 600 ~/.ssh/travis_rsa
- mv -fv .travis/config ~/.ssh/config

# 安装hexo以及一些插件，没用到的可移除相关命令
install:
- npm install hexo-cli -g
- npm install hexo-math --save
- npm install hexo-generator-searchdb --save
- npm install hexo-symbols-count-time --save
- npm install hexo-generator-feed --save
- npm install hexo-wordcount --save
- npm install mermaid --save
- npm install hexo-tag-mermaid --save
- npm install hexo-tag-plantuml --save

# 安装next主题插件，没用到的可移除相关命令
before_script:
- cd ./themes/next
- git clone https://github.com/theme-next/theme-next-fancybox3 source/lib/fancybox
- git clone https://github.com/theme-next/theme-next-jquery-lazyload source/lib/jquery_lazyload
- git clone https://github.com/theme-next/theme-next-needmoreshare2 source/lib/needsharebutton
- git clone https://github.com/theme-next/theme-next-pace source/lib/pace
- git clone https://github.com/theme-next/theme-next-pangu.git source/lib/pangu
- git clone https://github.com/theme-next/theme-next-reading-progress source/lib/reading_progress
- cd ..
- cd ..

# 构建博客
script:
- hexo -version
- hexo clean && hexo g

after_script:
# 设置环境
- set -ev
- export TZ='Asia/Shanghai'
- cd ./public
# 提交
- git config user.name "tauzoye"  # 你的github用户名
- git config user.email "893239209@qq.com"  # 你的github邮箱
- git init
- git add .
- git commit -m "Site updated:`date +"%Y-%m-%d %H:%M:%S"`"
# push
- git remote add coding git@git.coding.net:tauzoye/tauzoye.git  # USERNAME为你的coding用户名
- git remote add gitee git@gitee.com:tauzoye/tauzoye.git  # USERNAME为你的gitee用户名
- git push -u origin master -f
- git push -u coding master -f
- git push -u gitee master -f
